@startuml

node "<<modbile device>> Player" as PlayerOne {
    package "Game" {
        component "GameServer" as P1GameServer
        component "GameClient" as P1GameClient
    }
}

database "<<database>> Firebase Realtime Database" as Firebase

P1GameClient --> Firebase : <<use>>
P1GameServer --> Firebase : <<use>>

@enduml