@startuml

package "launcher" {
    
}

package "gamecore" {
    
}

package "input" {
    
}

package "networking" {
    
}

package "sound" {
    
}

' package "utils" {
    
' }

package "graphics" {
    
}

launcher --> gamecore : creates
launcher --> input : uses
launcher --> networking : uses
launcher --> sound : uses
' launcher --> utils : uses
launcher --> graphics : uses

input --> gamecore : implements
networking --> gamecore : implements
sound --> gamecore : implements
' utils --> gamecore : implements
graphics --> gamecore : implements

@enduml
