@startmindmap "Updated Utility Tree"
* Utility
** Modifiability
*** Add a new Enemy type
**** (H, L) Add enemy in < 3 person hours.
*** Add a new Element card
**** (H, L) Add element-card in < 3 person hours.
*** Add a new Map
**** (H, L) Add map in < 3 person hours.
** Usability
*** New player plays the tutorial
**** (M, M) User learns game via tutorial in < 3 minutes
*** Sell tower
**** (H, M) Towers should be sold in < 2 seconds, and the player should be reimbursed
*** Pause/Resume game
**** (M, L) The game should pause or unpause in < 2 seconds upon press of pause/resume-button
*** One player loses connection
**** (H, L) Player is kicked out after connection is lost for more than 30 seconds, otherwise resume play
** Performance
*** Singleplayer performance
**** (H, H) End-to-end delay < 40 ms
*** Multiplayer performance
**** (H, H) End-to-end delay < 40 ms given stable internet
** Availability
*** Database availability
**** (H, L) Uptime > 99%
*** Server availability
**** (H, L) Server should always be available
@endmindmap


#Parentesene betyr følgende: 
#Definisjon:
#(A, B) = (Business Value, Effort)

#Eksempler:
#(H, H) = High Business Value, High Effort
#(M, M) = Medium Business Value, Medium Effort
#osv...